version: "3.3"
services:
  backendApp:
    image: "AppImage:v1.0"
    tty: true
    deploy:
      replicas: 1
    ports:
      - 80:80
    volumes:
      - backendLogs:/var/log/apache2
  
volumes:
  backendLogs:
